allprojects {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

//buildscript {
//    ext.kotlin_version = '2.1.0'
//    repositories {
//        google()
//        maven { url "https://jitpack.io" }
//        mavenCentral()
//    }
//
//    dependencies {
//        classpath 'com.android.tools.build:gradle:8.6.1'
//        classpath 'com.google.gms:google-services:4.4.3'
//        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
//        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
//    }
//}
//
//plugins {
//    id "com.android.application" version "8.5.2" apply false
//    id "com.android.library"    version "8.5.2" apply false
//    id "org.jetbrains.kotlin.android" version "1.9.24" apply false
//}
//
//allprojects {
//    repositories {
//        google()
//        mavenCentral()
//        maven { url "https://jitpack.io" }
//    }
//}
//
//rootProject.buildDir = '../build'
//subprojects {
//    project.buildDir = "${rootProject.buildDir}/${project.name}"
//}
//subprojects {
//    project.evaluationDependsOn(':app')
//}
//
//tasks.register("clean", Delete) {
//    delete rootProject.buildDir
//}
