# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Upload new uat build to App Center"
  lane :uat do
    gradle(flavor: "uat", task: "bundle", build_type: "Release", flags: "-Ptarget=lib/main.dart")
    # gradle(flavor: "dev", task: "bundle", build_type: "Release", flags: "-Ptarget=lib/main.dart")
    appcenter_upload(
      api_token: "8fedfd3970fd73c1b0a4dec5f4e0656296cb978c",
      owner_name: "khieunguyen95",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "SBA-CMV-UAT",
      destinations: "*",
      file: "/Users/nguyentruongkhieu/Desktop/project/vinorsoft/sba/build/app/outputs/bundle/uatRelease/app-uat-release.aab",
      notify_testers: true, # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  
  end
end
