// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'chcc_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CHCCInfo _$CHCCInfoFromJson(Map<String, dynamic> json) => CHCCInfo(
      assetId: json['assetId'] as String?,
      assetCode: json['assetCode'] as String?,
      landPlotNumber: json['landPlotNumber'] as String?,
      mapSheetNumber: json['mapSheetNumber'] as String?,
      realAddressDetail: json['realAddressDetail'] as String?,
      realAddressStreet: json['realAddressStreet'] as String?,
      realAddressWard: json['realAddressWard'] as String?,
      realAddressDistrict: json['realAddressDistrict'] as String?,
      realAddressProvince: json['realAddressProvince'] as String?,
      legalAddressDetail: json['legalAddressDetail'] as String?,
      legalAddressStreet: json['legalAddressStreet'] as String?,
      legalAddressWard: json['legalAddressWard'] as String?,
      legalAddressDistrict: json['legalAddressDistrict'] as String?,
      legalAddressProvince: json['legalAddressProvince'] as String?,
      legalApartmentNumber: json['legalApartmentNumber'] as int?,
      numberBasement: json['numberBasement'] as int?,
      nameBuilding: json['nameBuilding'] as String?,
      mainRoadWith: (json['mainRoadWith'] as num?)?.toDouble(),
      positionId: json['positionId'] as int?,
      legalApartmentCode: json['legalApartmentCode'] as String?,
      legalFloorNo: json['legalFloorNo'] as int?,
      legalNumberBedroom: json['legalNumberBedroom'] as int?,
      legalNumberToilets: json['legalNumberToilets'] as int?,
      legalFurniture: json['legalFurniture'] as String?,
      legalFacades: json['legalFacades'] as int?,
      legalMainBalconyDirection: json['legalMainBalconyDirection'] as String?,
      legalPrivateUseArea: (json['legalPrivateUseArea'] as num?)?.toDouble(),
      legalClearanceArea: (json['legalClearanceArea'] as num?)?.toDouble(),
      legalBuildupArea: (json['legalBuildupArea'] as num?)?.toDouble(),
      legalExtendArea: (json['legalExtendArea'] as num?)?.toDouble(),
      realApartmentCode: json['realApartmentCode'] as String?,
      realFloorNo: json['realFloorNo'] as int?,
      realNumberBedroom: json['realNumberBedroom'] as int?,
      realNumberToilets: json['realNumberToilets'] as int?,
      realFurniture: json['realFurniture'] as String?,
      realFacades: json['realFacades'] as int?,
      realMainBalconyDirection: json['realMainBalconyDirection'] as String?,
      realPrivateUseArea: (json['realPrivateUseArea'] as num?)?.toDouble(),
      realClearanceArea: (json['realClearanceArea'] as num?)?.toDouble(),
      realBuildupArea: (json['realBuildupArea'] as num?)?.toDouble(),
      realExtendArea: (json['realExtendArea'] as num?)?.toDouble(),
      realBuilding: json['realBuilding'] as String?,
      numberFloors: json['numberFloors'] as int?,
      note: json['note'] as String?,
      assetApartmentInforId: json['assetApartmentInforId'] as int?,
      totalApartmentArea: (json['totalApartmentArea'] as num?)?.toDouble(),
      uses: json['uses'] as String?,
      usingPurposeTypeId: json['usingPurposeTypeId'] as String?,
      termOfLandUse: json['termOfLandUse'] as String?,
      description: json['description'] as String?,
      utilities: json['utilities'] as String?,
      legalCurrentPrivateUsing: json['legalCurrentPrivateUsing'] as String?,
      realCurrentPrivateUsing: json['realCurrentPrivateUsing'] as String?,
    );

Map<String, dynamic> _$CHCCInfoToJson(CHCCInfo instance) => <String, dynamic>{
      'assetId': instance.assetId,
      'assetCode': instance.assetCode,
      'assetApartmentInforId': instance.assetApartmentInforId,
      'landPlotNumber': instance.landPlotNumber,
      'mapSheetNumber': instance.mapSheetNumber,
      'realAddressDetail': instance.realAddressDetail,
      'realAddressStreet': instance.realAddressStreet,
      'realAddressWard': instance.realAddressWard,
      'realAddressDistrict': instance.realAddressDistrict,
      'realAddressProvince': instance.realAddressProvince,
      'legalAddressDetail': instance.legalAddressDetail,
      'legalAddressStreet': instance.legalAddressStreet,
      'legalAddressWard': instance.legalAddressWard,
      'legalAddressDistrict': instance.legalAddressDistrict,
      'legalAddressProvince': instance.legalAddressProvince,
      'legalApartmentNumber': instance.legalApartmentNumber,
      'numberBasement': instance.numberBasement,
      'nameBuilding': instance.nameBuilding,
      'mainRoadWith': instance.mainRoadWith,
      'positionId': instance.positionId,
      'legalApartmentCode': instance.legalApartmentCode,
      'legalFloorNo': instance.legalFloorNo,
      'legalNumberBedroom': instance.legalNumberBedroom,
      'legalNumberToilets': instance.legalNumberToilets,
      'legalFurniture': instance.legalFurniture,
      'legalFacades': instance.legalFacades,
      'legalMainBalconyDirection': instance.legalMainBalconyDirection,
      'legalPrivateUseArea': instance.legalPrivateUseArea,
      'legalClearanceArea': instance.legalClearanceArea,
      'legalBuildupArea': instance.legalBuildupArea,
      'legalExtendArea': instance.legalExtendArea,
      'legalCurrentPrivateUsing': instance.legalCurrentPrivateUsing,
      'realApartmentCode': instance.realApartmentCode,
      'realFloorNo': instance.realFloorNo,
      'realNumberBedroom': instance.realNumberBedroom,
      'realNumberToilets': instance.realNumberToilets,
      'realFurniture': instance.realFurniture,
      'realFacades': instance.realFacades,
      'realMainBalconyDirection': instance.realMainBalconyDirection,
      'realPrivateUseArea': instance.realPrivateUseArea,
      'realClearanceArea': instance.realClearanceArea,
      'realBuildupArea': instance.realBuildupArea,
      'realExtendArea': instance.realExtendArea,
      'realBuilding': instance.realBuilding,
      'realCurrentPrivateUsing': instance.realCurrentPrivateUsing,
      'numberFloors': instance.numberFloors,
      'note': instance.note,
      'description': instance.description,
      'totalApartmentArea': instance.totalApartmentArea,
      'uses': instance.uses,
      'usingPurposeTypeId': instance.usingPurposeTypeId,
      'termOfLandUse': instance.termOfLandUse,
      'utilities': instance.utilities,
    };
